### ISSUE TITLE
Error al mostrar el modelo en rviz (fixed frame [map] does not exist)

### ISSUE THREAD

**Issue by dacruizac** [jmfajardod/test_description_rycsv#1]
Cuando se ejecuta el archivo view_model.launch abre correctamente rviz, y no se ven errores en la consola, pero no se muestra ningún modelo en rviz. Dentro de la ventana de rviz aparece un error: (fixed frame [map] does not exist). No se como arreglar ese error

![Captura de pantalla de 2020-09-25 17-16-30](https://user-images.githubusercontent.com/43124793/94320571-edc91180-ff52-11ea-851b-ca6f10d8248b.png)

**Comment by jmfajardod** [comment]
Buenas tardes, el error es porque el marco de referencia "map" no existe. En la sesión práctica de ayer Viernes 25, mostre como arreglar esto. Para arregrarlo es necesario dar click sobre "map" en la propiedad "Fixed frame" y seleccionar un marco de referencia disponible. Para añadir el modelo del robot es necesario darle click en "Add" en la esquina inferior izquierda y agregar la propiedad "RobotModel".
